version: "2"

linters:
  default: none
  enable:
    - loglint

  settings:
    custom:
      loglint:
        type: module
        description: linter for reporting log messages
        original-url: github.com/leoscrowi/loglint
        settings:
          one: Foo